# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_added', '-order'), 'verbose_name': 'portfólio', 'verbose_name_plural': 'portfólios'},
        ),
        migrations.AddField(
            model_name='post',
            name='date_added',
            field=models.DateField(blank=True, null=True, verbose_name='adicionado em'),
        ),
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.PositiveIntegerField(default=9999, verbose_name='ordem'),
        ),
    ]
